name: estima_ai_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.4+2305301

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  dio: ^4.0.6
  http: ^0.13.4
  url_launcher: ^6.0.18
  flutter_spinkit: ^5.1.0
  connectivity: ^3.0.6
  shared_preferences: ^2.0.12
  flutter_secure_storage: ^7.0.0
  uuid: ^3.0.5
  shimmer: ^2.0.0
  intl: ^0.17.0
  badges: ^2.0.2
  dotted_border: ^2.0.0+2
  eva_icons_flutter: ^3.0.2
  currency_text_input_formatter: ^2.1.8
  dropdown_search: ^2.0.1
  pinput: ^2.1.4
  pointycastle: ^3.6.0
  firebase_analytics:
  local_auth: ^2.1.2
  flutter_switch: ^0.3.2
  local_session_timeout: ^2.2.0
  syncfusion_flutter_pdf: ^20.4.50
  open_filex: ^4.3.2


  flutter_localizations:
    sdk: flutter
  sentry_flutter: ^6.9.1


  #firebase
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0

  #  for finding commonly used locations in the filesystem
  path_provider: ^2.0.9
  #plugin to get the downloads directory on Android,
  external_path: ^1.0.1
  #plugin to check and request permissions
  permission_handler: ^10.2.0
  #plugin for displaying local notifications
  flutter_local_notifications: ^13.0.0

  #local modules
  core:
    path: core


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0
  build_runner: ^2.1.7


flutter:
  generate: true
  uses-material-design: true

  assets:
    - images/
    - images/menu/
    - assets/
    - assets/certificate/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 200
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Archivo
      fonts:
        - asset: fonts/Archivo-Regular.ttf
          weight: 400
        - asset: fonts/Archivo-Medium.ttf
          weight: 200
        - asset: fonts/Archivo-SemiBold.ttf
          weight: 500
        - asset: fonts/Archivo-Bold.ttf
          weight: 700
