name: core
description: A new Flutter package project.
version: 0.0.1
#homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  dio: ^4.0.6
  http: ^0.13.4
  pretty_dio_logger: ^1.1.1
  logger: ^1.1.0
  connectivity: ^3.0.6
  flutter_svg: ^2.0.0+1
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  flutter_secure_storage: ^7.0.0

  file_picker: ^5.2.5
  image_picker: ^0.8.4+6
  path_provider: ^2.0.8
  external_path: ^1.0.1
  permission_handler: ^10.2.0
  image: ^4.0.13
  extended_masked_text: ^2.3.1
  dotted_border: ^2.0.0+2
  get_it: ^7.2.0
  flutter_local_notifications: ^13.0.0
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/localization/

